# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'PopStats' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PopStats
  pod 'SwiftyJSON', '2.3.1'
  pod 'Charts', '2.2.3'

  target 'PopStatsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
